### PR TITLE
:sparkles: add all webhook events for pipeline

### LINKED ISSUE #17: Add post when a pipeline fail
Fix this todo https://github.com/manland/mattermost-plugin-gitlab/pull/16/files#diff-f5423ed5cd60421ed7d6afba24d23d86R26

### PR DESCRIPTION
**Pull request by manland**
Fix #17

### CODE REVIEW

File: server/webhook/pipeline.go [hunk 1]
```diff
@@ -42,26 +51,35 @@ func (w *webhook) handleChannelPipeline(event *gitlab.PipelineEvent) ([]*HandleW
 	senderGitlabUsername := event.User.Username
 	repo := event.Project
 	res := []*HandleWebhook{}
+	message := ""
 
-	message := fmt.Sprintf("[%s](%s) New pipeline by [%s](%s) for [%s](%s)", repo.PathWithNamespace, repo.WebURL, senderGitlabUsername, w.gitlabRetreiver.GetUserURL(senderGitlabUsername), event.Commit.Message, event.Commit.URL)
+	if event.ObjectAttributes.Status == "running" {
```
Comment (hanzei) [inline server/webhook/pipeline.go]: Use `switch`?
