### PR TITLE
:bug: user not logged can see help command

### LINKED ISSUE #49: Help command should be available before the user is connected
Help for the command is provided in the form of a DM from the BOT once connected but, it would also be good to have /gitlab help available to the user before they authenticate to show connect and the other commands.

### PR DESCRIPTION
**Pull request by manland**
Fix #49

### CODE REVIEW

File: server/command.go [hunk 1]
```diff
@@ -77,6 +77,9 @@ func (p *Plugin) ExecuteCommand(c *plugin.Context, args *model.CommandArgs) (*mo
 
 		resp := p.getCommandResponse(model.COMMAND_RESPONSE_TYPE_EPHEMERAL, fmt.Sprintf("[Click here to link your GitLab account.](%s/plugins/%s/oauth/connect)", *config.ServiceSettings.SiteURL, manifest.Id))
 		return resp, nil
+	} else if action == "help" || action == "" {
```
Comment (hanzei) [inline server/command.go]: Nit: You can drop the `else`

Comment (manland) [reply server/command.go]: :+1:

**Comment by manland** [comment]
Again and again very thank yu @hanzei !
